server:
  port: 5000
spring:
  application:
    name: api-gateway
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:3306/gateway?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    properties:
      sslMode: DISABLED
    pool:
      enabled: true
      initial-size: 22
      max-size: 30
      max-idle-time: 5m
      validation-query: SELECT 1
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: Origin, Accept, Content-Type, X-Requested-With, X-XSRF-TOKEN, Authentication, Authorization, Version, X-API-KEY, X-PRINCIPAL
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/api-gateway}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
          - gateway
  profiles:
    active: dev, local
application:
  formatted-version: (v1.0.0)
  base-url: gateway
  route-mode: dynamic
services:
  notification-service:
    name: notification-service
    url:  https://notification.com
  security-service:
    name: security-service
    url:  https://security.com
domain:
  tenant:
    alias: fl
    id: 1