server:
  port: 5000
spring:
  application:
    name: api-gateway
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/gateway?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    properties:
      sslMode: DISABLED
    pool:
      enabled: true
      initial-size: 22
      max-size: 30
      max-idle-time: 5m
      validation-query: SELECT 1
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: Origin, Accept, Content-Type, X-Requested-With, X-XSRF-TOKEN, Authentication, Authorization, Version, X-API-KEY, X-PRINCIPAL
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      config:
        format: files
        prefixes: ${CONSUL_CONFIGS_TAG:app/configs/api-gateway}
        watch:
          delay: 5000
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        tags:
          - java
          - spring
          - gateway
  profiles:
    active: dev, cors, local
application:
  formatted-version: (v1.1.0)
  base-url: gateway
  route-mode: dynamic
services:
  notification-service:
    name: notification-service
    url:  https://notification.com
  security-service:
    name: security-service
    url:  https://security.com
domain:
  tenant:
    alias: fl
    id: 1
sentry:
  dsn: https://f0aa547a7df247a190c11bb8fecb4fab@o1200481.ingest.sentry.io/6324453
  traces-sample-rate: 1.0
  environment: production
  sample-rate: 1.0
  release: inventory@1.1.0