server:
  port: 5000
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gateway
    username: root
    password:
    properties:
      sslMode: DISABLED
    pool:
      enabled: true
      initial-size: 22
      max-size: 30
      max-idle-time: 5m
      validation-query: SELECT 1
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"